### ISSUE TITLE
error: unrecognized command line option ‘-rdynamic’ while trying to build on Linux

### ISSUE THREAD

**Issue by supern64** [JoshuaWise/integer#10]
Hello, I've been trying to build integer on Ubuntu 18.04.1, I installed GCC and renamed it and used the POSIX version, while trying to build it, I get this error.
```
dbr@raze:~/DBR$ npm install better-sqlite-pool

> integer@1.0.7 install /home/dbr/DBR/node_modules/integer
> node-gyp rebuild

make: Entering directory '/home/dbr/DBR/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
../src/integer.cpp: In static member function ‘static Result Integer::Cast(v8::Local<v8::String>, uint8_t)’:
../src/integer.cpp:329:33: warning: ‘v8::String::Value::Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   v8::String::Value utf16(string);
                                 ^
In file included from /home/dbr/.node-gyp/11.4.0/include/node/v8.h:26:0,
                 from /home/dbr/.node-gyp/11.4.0/include/node/node.h:63,
                 from ../src/integer.hpp:3,
                 from ../src/integer.cpp:1:
/home/dbr/.node-gyp/11.4.0/include/node/v8.h:3016:51: note: declared here
     V8_DEPRECATED("Use Isolate version", explicit Value(Local<v8::Value> obj));
                                                   ^
/home/dbr/.node-gyp/11.4.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/integer.node
g++: error: unrecognized command line option ‘-rdynamic’
integer.target.mk:132: recipe for target 'Release/obj.target/integer.node' failed
make: *** [Release/obj.target/integer.node] Error 1
make: Leaving directory '/home/dbr/DBR/node_modules/integer/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dbr/DBR/node_modules/integer
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN enmap@4.5.0 requires a peer of better-sqlite-pool@github:eslachance/better-sqlite-pool but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dbr/.npm/_logs/2018-12-15T07_25_20_581Z-debug.log
```
Here's the version of GCC used.
```
dbr@raze:~/DBR$ g++ --version
g++ (GCC) 7.3-posix 20180312
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.```

**Comment by supern64** [comment]
Never mind, I installed another version of g++ and it worked.
