### ISSUE TITLE
Error when using "npm install"

### ISSUE THREAD

**Issue by Noxillio** [JoshuaWise/integer#13]
Windows 10 Build 17763.253
Node v10.15.0
npm v6.4.1

```
PS C:\users\noxillio\documents\github\yum> npm i

> integer@2.1.0 install C:\users\noxillio\documents\github\yum\node_modules\integer
> node-gyp rebuild


C:\users\noxillio\documents\github\yum\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  integer.cpp
  win_delay_load_hook.cc
..\src\integer.cpp(370): warning C4804: '-': unsafe use of type 'bool' in operation [C:\users\noxillio\documents\github
\yum\node_modules\integer\build\integer.vcxproj]
C:\Users\Noxillio\.node-gyp\10.15.0\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x226
2F2 [C:\users\noxillio\documents\github\yum\node_modules\integer\build\integer.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\users\noxillio\documents\github\yum\node_modules\integer
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN discord-akairo@8.0.0-dev requires a peer of sqlite@^2.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord-akairo@8.0.0-dev requires a peer of sequelize@^4.38.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@12.0.0-dev requires a peer of zlib-sync@^0.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN enmap@4.6.2 requires a peer of better-sqlite-pool@github:eslachance/better-sqlite-pool but none is installed. You must install peer dependencies yourself.
npm WARN yumalpha@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Noxillio\AppData\Roaming\npm-cache\_logs\2019-01-21T21_23_14_936Z-debug.log
```

**Comment by JoshuaWise** [comment]
> fatal error LNK1106: invalid file or disk full: cannot seek to 0x226

It looks like this is an issue with your machine and not the `integer` package.

**Comment by Noxillio** [comment]
@JoshuaWise My disk is most certainly not full, so I'd like to know why this is happening

![image](https://user-images.githubusercontent.com/40806092/51500164-191d5580-1d9b-11e9-9750-a7d2c0452db3.png)

**Comment by Noxillio** [comment]
Maybe it's worth mentioning that just before that particular line I have a warning:

`..\src\integer.cpp(370): warning C4804: '-': unsafe use of type 'bool' in operation
[C:\users\Noxillio\Documents\github\yum\node_modules\integer\build\integer.vcxproj]`




EDIT: I ended up deleting my `.node-gyp` folder and I did not get the error this time. Seems it's resolved now.

**Comment by JoshuaWise** [comment]
@Noxillio Glad to here it. Whatever the issue was, it couldn't have been related to `integer` because this package doesn't do anything special during the installation. Even the warning you mention above wouldn't be related because that warning is about runtime code, not installation code. It's possible the issue was related to `node-gyp`, though.
