### ISSUE TITLE
ERR Failed at the integer@4.0.0 install script 'prebuild-install || npm run build-release

### ISSUE THREAD

**Issue by CJB314** [JoshuaWise/integer#30]
I know this is a common error, but should just running a VM fix this? I've tried all the other fixes and nothing worked

**Comment by JoshuaWise** [comment]
Please give more details on the error that occurred.

**Comment by haroldallen** [comment]
Same problem - here is error:
`PS C:\Users\09Coo\Desktop\Dev\Bot\DiscBot> npm i integer

> integer@4.0.0 install C:\Users\09Coo\Desktop\Dev\Bot\DiscBot\node_modules\integer
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=12.18.1 runtime=node arch=x64 libc= platform=win32)

> integer@4.0.0 build-release C:\Users\09Coo\Desktop\Dev\Bot\DiscBot\node_modules\integer
> node-gyp rebuild --release


C:\Users\09Coo\Desktop\Dev\Bot\DiscBot\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.7.30406.217) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\09Coo\Desktop\Dev\Bot\DiscBot\node_modules\integer
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@4.0.0 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@4.0.0 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\09Coo\AppData\Roaming\npm-cache\_logs\2020-08-14T17_11_55_295Z-debug.log
npm WARN discbot@0.9.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@4.0.0 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\09Coo\AppData\Roaming\npm-cache\_logs\2020-08-14T17_11_55_403Z-debug.log`

**Comment by Crumblegdl** [comment]
I have this same issue. Seems to be preventing me from updating to node v16.6

any luck? Have tried google everything related to node-gyp. reinstalled all build tools, reinstalled node v16.6 with all dependencies and rebooting. literally cannot get past thing. soon as i revert to node v14 all problems go away.
